Refactoring to debug frontend smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -405,7 +405,7 @@ jobs:
     
   deploy-frontend:
     docker:
-      - image: amazon/aws-cli
+      - image: circleci/node:13.8.0 # amazon/aws-cli
     steps:
       - checkout
       - run:
@@ -415,6 +415,7 @@ jobs:
             yum -y install gzip
             curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
             yum -y install nodejs
+            npm install
       - attach_workspace:
           at: ./
       - run:
@@ -434,6 +435,14 @@ jobs:
             echo NODE_ENV=production >> "frontend/.env"
             cat "frontend/.env"
       - run:
+          name: Add aws-cli
+          command: |
+            sudo apt-get update
+            #sudo apt-get install awscli
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - run:
           name: Deploy frontend objects
           command: |
             export API_URL=$(cat .circleci/api_url.txt)
@@ -442,6 +451,7 @@ jobs:
             npm install
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws --version
             aws s3 sync dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --acl public-read --delete
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -513,18 +523,19 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-eu-west-2.amazonaws.com/#/employees"  
-            
-            echo ${URL}
 
-            if curl -s ${URL} | grep "Welcome"
+            curl --connect-timeout 10 -s http://udapeople-<< pipeline.parameters.run_id >>.s3-website-eu-west-2.amazonaws.com | grep "Welcome"
+            retval=$?
+
+            echo $retval
+
+            if [ $retval -eq 0 ]
             then
-              echo "Frontend smoke test successful."
+              echo "Frontend OK"
               exit 0
             else
-              echo "Frontend smoke test unsuccessful."
+              echo "Backend Fail"
               exit 1
-            fi        
       - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - destroy-environment:  
